### ISSUE TITLE
The great code migration

### ISSUE THREAD

**Issue by Rodney-Lewis** [FRC-1250/Team-1250-DestinationDeepSpace#1]
Move over any useful code from the 2018 robot. This is most likely just the drive train and basic auto drive methods.

**Comment by Rodney-Lewis** [comment]
Drivetrain subsystem.
https://github.com/FRC-1250/Team-1250-PowerUp-Code/blob/master/src/org/usfirst/frc/team1250/robot/subsystems/Sub_DriveTrain.java

These as well.
https://github.com/FRC-1250/Team-1250-PowerUp-Code/blob/master/src/org/usfirst/frc/team1250/robot/subsystems/Sub_NewIntake.java

https://github.com/FRC-1250/Team-1250-PowerUp-Code/blob/master/src/org/usfirst/frc/team1250/robot/subsystems/Sub_LimeLight.java

**Comment by ruiqim** [comment]
is the CTRE extension still necessary?

**Comment by Rodney-Lewis** [comment]
Probably not. 

So far it sounds like sparks are going everywhere unless they disappoint somehow.

**Comment by ruiqim** [comment]
Has the Drivetrain been fully migrated now?

**Comment by Rodney-Lewis** [comment]
According to @RincewindBoi it has. Not worried about the auton movement logic as the methods we used to get the encoder data changed slightly.

Limelight has also been moved over.

**Comment by Rodney-Lewis** [comment]
Will close this and revisit later if needed. Drive logic has been moved and updated accordingly here - b234a2598b58ce7a847cee3b99f2e18c104acd65
