### ISSUE TITLE
Need a review on Sub_drive train . Very important, check everything

### ISSUE THREAD

**Issue by RincewindBoi** [FRC-1250/Team-1250-DestinationDeepSpace#22]
Does this all look right in the armwork branch?
Thanks

**Comment by ruiqim** [comment]
why?

**Comment by ruiqim** [comment]
// ⠀⠀⠀⠀⣀⣤
// ⠀⠀⠀⠀⣿⠿⣶
// ⠀⠀⠀⠀⣿⣿⣀
// ⠀⠀⠀⣶⣶⣿⠿⠛⣶
// ⠤⣀⠛⣿⣿⣿⣿⣿⣿⣭⣿⣤
// ⠒⠀⠀⠀⠉⣿⣿⣿⣿⠀⠀⠉⣀
// ⠀⠤⣤⣤⣀⣿⣿⣿⣿⣀⠀⠀⣿
// ⠀⠀⠛⣿⣿⣿⣿⣿⣿⣿⣭⣶⠉
// ⠀⠀⠀⠤⣿⣿⣿⣿⣿⣿⣿
// ⠀⠀⠀⣭⣿⣿⣿⠀⣿⣿⣿
// ⠀⠀⠀⣉⣿⣿⠿⠀⠿⣿⣿
// ⠀⠀⠀⠀⣿⣿⠀⠀⠀⣿⣿⣤
// ⠀⠀⠀⣀⣿⣿⠀⠀⠀⣿⣿⣿
// ⠀⠀⠀⣿⣿⣿⠀⠀⠀⣿⣿⣿
// ⠀⠀⠀⣿⣿⠛⠀⠀⠀⠉⣿⣿
// ⠀⠀⠀⠉⣿⠀⠀⠀⠀⠀⠛⣿
// ⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⣿⣿
// ⠀⠀⠀⠀⣛⠀⠀⠀⠀⠀⠀⠛⠿⠿⠿
// ⠀⠀⠀⠛⠛

**Comment by ruiqim** [comment]
everything else looks fine...

**Comment by FRC-1250** [comment]
> everything else looks fine...

Shhh

**Comment by Rodney-Lewis** [comment]
Make a pull request buddy, that's what they're for. Collector updates we're already merged into master a few days ago by Eseniya.

But everything here should build fine. Just fyi, use /**/ instead of // for long multi line comments!
