### ISSUE TITLE
Limelight - Detected object pursuit logic

### ISSUE THREAD

**Issue by Rodney-Lewis** [FRC-1250/Team-1250-DestinationDeepSpace#8]
Current limelight logic to pursue objects needs some refinement based on tests done.

**Comment by Rodney-Lewis** [comment]
Apart of the issue is due to the lack of deadband that exists. Case study on the limelight website shows an example of implementing the deadband AND handling very small values using a 'min' value. http://docs.limelightvision.io/en/latest/cs_aiming.html

```
float Kp = -0.1f;
float min_command = 0.05f;

std::shared_ptr<NetworkTable> table = NetworkTable::GetTable("limelight");
float tx = table->GetNumber("tx");

if (joystick->GetRawButton(9))
{
        float heading_error = -tx;
        float steering_adjust = 0.0f;
        if (tx > 1.0)
        {
                steering_adjust = Kp*heading_error - min_command;
        }
        else if (tx < 1.0)
        {
                steering_adjust = Kp*heading_error + min_command;
        }
        left_command += steering_adjust;
        right_command -= steering_adjust;
}
```

**Comment by FRC-1250** [comment]
Updated logic was included here - https://github.com/FRC-1250/Team-1250-DestinationDeepSpace/commit/0b400d812e87cf512f8403369a027b15316f16ad#diff-e38d24d09e11aeca152a759bc5854216

in commit 0b400d812e87cf512f8403369a027b15316f16ad

Create a pull request when possible as we know this driving logic works. It will just need to be fine tuned for the competition robot.
