### ISSUE TITLE
Tower - Move to position

### ISSUE THREAD

**Issue by FRC-1250** [FRC-1250/Team-1250-DestinationDeepSpace#9]
Currently the tower will have to be able to hit 8 different positions based on the various heights that exists in the game.
1 - Home (Starting position)
2 - Loading Station, Rocket ship hatch level 1, Cargo ship hatch
3 - Cargo ship cargo bay
4 - Rocket ship hatch level 2
5 - Rocket ship hatch level 3
6 - Rocket cargo bay level 1
7 - Rocket cargo bay level 2 
8 - Rocket cargo bay level 3

While moving to these positions we'll need to add a safety feature to help prevent twisting of the arm as it'll be driven by two separate motors. The cases for that would be:

1 - Left and Right are equivalent
2 - Left faster then Right
3 - Left slower then Right
4 - Left is stuck, Right is moving
5 - Right is stuck, Left is moving

For cases 2 and 3, we can scale the speed so we always match the slower one OR we can allow for some catch up mechanism.

For cases 4 and 5, we need to be able to recognize one side isn't moving and kill the motor controller group completely until the side that is stuck can move towards the position of the one that can move.

**Comment by Rodney-Lewis** [comment]
A solution we discussed today. Could also add the cases where one arm is stuck there is another threshold, Z, that we completely stop one (or slow down) one side to allow the other to catch up.

X - denotes the current speed
T - denotes the increase we would add
Y - denotes the threshold to check
```
Execute() {
If (armsHealthCheck() == 0)
   DriveBoth(x)
else if (armsHealthCheck() == 1)
  DriveD1(x)
  DriveD2(x + t)
else if (armsHealthCheck() == 2)
  DriveD1(x + t)
  DriveD2(x)
}

ArmsHealthCheck() { 
Difference = D1Ticks - D2Tickets

If(Absolute_value(Difference) > y)
   If(Difference > 0
      return 1
   else If(Difference < 0)
      return 2
else
   return 0
}
```

**Comment by Rodney-Lewis** [comment]
Robot ripped it's own arm off so testing has been postponed.
Movement logic has been setup here - https://github.com/FRC-1250/Team-1250-DestinationDeepSpace/commit/27484d31908849708469cb9c18aa660b7e46626c
and here https://github.com/FRC-1250/Team-1250-DestinationDeepSpace/commit/2fea642b0e4f38c8c0bbbd266c0c3509f3ba63de

Still need to implement the anti joint twist method as described above.
